# Generated by Django 4.2.16 on 2024-11-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeinformation",
            options={"ordering": ["-login_at"]},
        ),
        migrations.RemoveField(
            model_name="employeeinformation",
            name="description",
        ),
        migrations.RemoveField(
            model_name="employeeinformation",
            name="is_success",
        ),
        migrations.RemoveField(
            model_name="employeeinformation",
            name="remote_addr",
        ),
        migrations.AddField(
            model_name="employeeinformation",
            name="logout_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
