# Generated by Django 4.2.16 on 2024-11-22 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_employeeinformation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeinformation",
            options={"ordering": ["-id"]},
        ),
        migrations.RemoveField(
            model_name="employeeinformation",
            name="login_at",
        ),
    ]
