# Generated by Django 4.2.16 on 2024-11-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_employeeinformation_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeinformation",
            name="late_minute",
            field=models.IntegerField(default=0),
        ),
    ]
