# Generated by Django 4.2.16 on 2024-11-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_takenannualleave_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeinformation",
            name="login_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
